apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-scripts
  namespace: default
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: kafka
    app.kubernetes.io/version: "2.5.0"
data:
  setup.sh: |-
    #!/bin/bash

    ID="${MY_POD_NAME#"kafka-"}"
    export KAFKA_CFG_BROKER_ID="$ID"

    exec /entrypoint.sh /run.sh
