apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: kafka
    app.kubernetes.io/version: "2.5.0"
spec:
  type: ClusterIP
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: kafka-client
    nodePort: null
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: kafka
